version: '2.3'

networks:
  proxy:
  database:

services:

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: CHANGEME4350238904328
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - proxy
      - database
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.wpnmx.rule=Host(``)"
      - "traefik.http.routers.wpnmx.rule=hostregexp(`{host:[a-z0-9-.]+}`)"
      - "traefik.http.routers.wpnmx.entrypoints=https"
      - "traefik.http.routers.wpnmx.tls.certresolver=letsencrypt"

  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: CHANGEME4350238904328
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - database


  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "9999:9999"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./traefik/acme:/etc/traefik/acme
      - ./traefik/dynamic:/etc/traefik/dynamic
      - ./traefik/log:/var/log/traefik
      - ./webusers:/etc/webusers:ro
    networks:
      - proxy
    command:
      - "--log.level=WARN"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.traefik.address=:9999"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      #- "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.email=wordpress@t.nmx.de"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
    labels:
      # global redirect to https
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:[a-z0-9-.]+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"


