version: '3.0'

networks:
  proxy:
  database:

services:

  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - db
    #ports:
    #  - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: CHANGEME4350238904328
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - proxy
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mywebsite.entrypoints=http"
      - "traefik.http.routers.mywebsite.rule=HostRegexp(`{host:[a-z0-9.]+}`)"
      #- "traefik.http.routers.mywebsite.entrypoints=https"
      #- "traefik.http.routers.mywebsite.rule=Host(`test.azlab.de`)"
      #- "traefik.http.routers.mywebsite.entrypoints=https"
      #- "traefik.http.routers.mywebsite.tls.certresolver=letsencrypt"

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: CHANGEME4350238904328
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - database


  traefik:
    image: traefik:latest
    restart: always
    ports:
      - "1180:80"
      - "11443:443"
      - "1999:9999"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme:/etc/traefik/acme
    networks:
      - proxy
    command:
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=mywebsite_proxy"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.traefik.address=:9999"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=wordpress-4452543@byom.de"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
      # remove for production
      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    labels:
      # global redirect to https
      - "traefik.enable=true"
      #- "traefik.http.routers.http-catchall.entrypoints=http"
      #- "traefik.http.routers.http-catchall.rule=hostregexp(`{host:[a-z0-9-.]+}`)"
      #- "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      #- "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      #- "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

